config/routes.rb
Rails.application.routes.draw do

  get 'session/new'
  get 'session/destroy'
  post 'session/create'

  resources :categories
  resources :forums
  resources :topics do
    resources :replies
  end

  root 'session#new'
  get 'new_session' => 'session#new', :as => :new_session

end

app/models/account.rb
# Account
class Account < ActiveRecord::Base
  has_many :replies
  has_many :topics
  has_many :ratings
  has_many :topics, through: :ratings
  belongs_to :internet_forum

  validates :name, presence: true, length: { maximum: 50 },
                   uniqueness: true
  VALID_EMAIL_REGEX = /\A[a-zA-Z0-9_.+\-]+@[a-zA-Z0-9\-]+\.[a-zA-Z0-9\-.]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :pass, presence: true, length: { minimum: 6 }
end

app/models/category.rb
# Category
class Category < ActiveRecord::Base
  belongs_to :internet_forum
  has_many :forums

  validates :description, length: {
    minimum: 10,
    maximum: 80
  }

  validates :name, presence: true
  validates :description, presence: true

  def add_forum(forum, user)
    forums.push(forum) if user.privilege == 'Administrator'
  end

  def remove_forum(forum_id, user)
    forums.delete(forum_id) if user.privilege == 'Administrator'
  end
end

app/models/forum.rb
# Forum
class Forum < ActiveRecord::Base
  belongs_to :category
  belongs_to :account
  has_many :topics

  validates :title, length: {
    minimum: 10,
    maximum: 80
  }

  # validates :account, presence: true
  validates :title, presence: true
  validates :description, presence: true

  def create_topic(topic)
    topics.push(topic)
  end

  def delete_topic(topic_id, user)
    topics.delete(topic_id) if user.privilege == 'Administrator' ||
      user.privilege == 'Moderator'
  end
end

app/models/internet_forum.rb
# InternetForum
class InternetForum < ActiveRecord::Base
  has_many :accounts
  has_many :categories

  validates :description, length: {
    minimum: 10,
    maximum: 80
  }

  validates :title, presence: true
  validates :description, presence: true

  def register_new_user(user)
    accounts.each { |account| return false if account.name == user.name }
    accounts.push user
  end

  def remove_user(user_id, user)
    if user.privilege == 'Administrator'
      accounts.delete(user_id)
      return
    else
      accounts.delete(user_id) if accounts.find(user_id).name == user.name
    end
  end

  def log_in(name, pass)
    found_account = nil
    accounts.each do |account|
      found_account = account if account.name == name
    end
    return 'user does not exist' if found_account.nil?
    return 'pasword is not correct' if found_account.pass != pass
    found_account
  end

  def add_category(category, user)
    categories.each { |cat| return false if category.name == cat.name }
    categories.push(category) if user.privilege.eql? 'Administrator'
  end

  def remove_category(category_id, user)
    categories.delete(category_id) if user.privilege == 'Administrator'
  end
end

app/models/rating.rb
# Rating
class Rating < ActiveRecord::Base
  belongs_to :topic
  belongs_to :account
end

app/models/reply.rb
# Reply
class Reply < ActiveRecord::Base
  belongs_to :account
  delegate :name, :to => :account, :prefix => true
  belongs_to :topic
  belongs_to :last_edit_by, class_name: 'Account',
    foreign_key: 'last_edit_by_id', validate: true
  has_and_belongs_to_many :replies, dependent: :destroy

  validates :account, presence: true

  def to_string
    ' reply owner: ' + account.name +
    "\n reply text: " + text
  end
end

app/models/topic.rb
# Topic
class Topic < ActiveRecord::Base
  belongs_to :account
  delegate :name, :to => :account, :prefix => true
  belongs_to :forum
  has_many :replies, dependent: :destroy
  has_many :ratings
  has_many :accounts, through: :ratings

  validates :title, length: {
    minimum: 10,
    maximum: 80
  }

  # validate :validate_ratings

  # def validate_ratings
  #   if !ratings.is_a?(Array) || ratings.detect{|r| !(1..5).include?(d)}
  #     errors.add(:ratings, :invalid)
  #   end
  # end

  validates :replies, presence: true
  validates :title, presence: true

  after_create :add_owner

  def add_owner
    update_attribute(:account, replies.first.account)
  end
  # def initialize(title)
  # @title = title
  # @replies = replies
  # @account = replies.first.account
  # @account.topics.push self
  # @users_who_rated = []
  # @ratings = []
  # end

  def add_reply(reply, *quotes)
    reply.replies = quotes
    replies.push reply
  end

  def remove_reply(user, reply)
    # index = self.replies.index(reply)
    user.privilege == 'Administrator' ? reply.destroy : false
  end

  def edit_reply(user, reply, text)
    # return false if user.replies.index(replies[id]).nil? && user.privilege !=
    #  'Administrator'
    return false if user.privilege != 'Administrator' &&
                   !user.replies.include?(reply)
    reply.update_attribute(:text, text)
    # reply.text = text
    reply.update_attribute(:last_edit_by, user)
  end

  def add_rating(user, stars)
    return false if stars < 1 || stars > 5
    # ind = @users_who_rated.index(user)
    rating = Rating.find_by(account_id: user.id, topic_id: id)
    if rating.nil?
      Rating.create('account' => user, 'topic' => self, 'rating' => stars)
    else
      rating.update_attribute(:rating, stars)
    end
  end
end

app/controllers/application_controller.rb
# application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/replies_controller.rb
# replies_controller.rb
class RepliesController < ApplicationController
  def create
    if !session[:user_id]
      redirect_to new_session_path
    else
      topic = Topic.find(params[:topic_id].to_i)
      account = Account.find(session[:user_id])
      reply = topic.replies.create(reply_params)
      reply.account = account
      reply.save
      redirect_to topic_path(topic)
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:text)
  end
end

app/controllers/session_controller.rb
# sesion_controller.rb
class SessionController < ApplicationController
  def new
    @account = Account.new
  end

  def create
    @internet_forum = InternetForum.first
    @account = @internet_forum.log_in(params[:account][:name],
                                      params[:account][:pass])
    if @account == 'user does not exist' || @account == 'pasword is not correct'
      redirect_to url_for(controller: :session, action: :new)
    else
      @forum = Forum.last
      session[:user_id] = @account.id
      redirect_to topics_path(@forum)
    end
  end

  def destroy
    if !session[:user_id].nil?
      session[:user_id] = nil
    else
      flash[:warning] = 'no one was logged in'
    end
    @forum = Forum.first
    redirect_to topics_path(@forum)
  end
end

app/controllers/topics_controller.rb
# topics_controller.rb
class TopicsController < ApplicationController
  def new
    if !session[:user_id].nil?
      @topic = Topic.new
    else
      # @forum = Forum.first
      redirect_to new_session_path
    end
  end

  def create
    if !session[:user_id]
      redirect_to new_session_path
    else
      @forum = Forum.first
      @account = Account.find(session[:user_id])
      @reply = Reply.create text: params[:description], account: @account
      @topic = @forum.topics.create(topic_params)
      @topic.add_reply(@reply)
      @topic.save
      redirect_to topics_path(@topic)
    end
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def index
    @topics = Topic.all
  end

  def edit
    unless session[:user_id]
      return redirect_to new_session_path
    end
    @user = Account.find(session[:user_id])
    @topic = Topic.find(params[:id])
    if @user.privilege != 'Administrator' && @topic.account != @user
      flash[:error] = 'You are not the owner of this reply!'
    end
    @topic
  end

  def update
    @topic = Topic.find(params[:id])

    if @topic.update(topic_params)
      redirect_to @topic
    else
      render 'edit'
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/helpers/application_helper.rb
# aa
module ApplicationHelper
end

app/helpers/replies_helper.rb
# sda
module RepliesHelper
end

app/helpers/session_helper.rb
# ads
module SessionHelper
end

app/helpers/topics_helper.rb
# asdd
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/replies/_reply.html.erb
<p>
  <strong>Commenter:</strong>
  <%= reply.account_name %>
</p>

<p>
  Reply:
  <%= reply.text %>
</p>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>
# <%= session.inspect %>

app/views/session/new.html.erb
<%= form_for :account, :url => url_for(:controller => 'session', :action => 'create') do |f| %>
  <% if @account.errors.any? %>
  <div id="error explanation">
    <h2><%= pluralize(@account.errors.count, "error") %> prohibited
      this account from being saved:</h2>
    <ul>
    <% @account.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field(:name) %>
  </p>
  <p>
    <%= f.label :pass %><br>
    <%= f.text_field :pass %>
  </p>
  <p>
    <%= f.submit "Login"%>
  </p>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<% if (!flash[:error]) %>
<%= form_for :topic, url: topic_path(@topic), method: :patch do |f| %>
  <% if @topic.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@topic.errors.count, "error") %> prohibited
      this topic from being saved:</h2>
    <ul>
    <% @topic.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<% else %>
<%= flash[:error] %>
<% end %>
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>
<%= link_to 'New topic', new_topic_path %> |
<% if (session[:user_id] == nil) %>
  <%= link_to 'Log in', url_for(:controller => :session, :action => :new) %>
<% else %>
  <%= link_to 'Log out', url_for(:controller => :session, :action => :destroy) %>
<% end %>
<br></br>
<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th colspan="2"></th>
  </tr>

  <% @topics.each do |topic| %>
    <tr>
      <td><%= topic.title %></td>
      <td><%= topic.account_name %></td>
      <td><%= link_to 'Show', topic_path(topic) %></td>
      <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    </tr>
  <% end %>
</table>

app/views/topics/new.html.erb
<%= form_for :topic, url: topics_path do |f| %>
  <% if @topic.errors.any? %>
  <div id="error explanation">
    <h2><%= pluralize(@topic.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @topic.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= label_tag(:description, "First reply:") %><br>
    <%= text_field_tag(:description) %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<h2>Replies</h2>
<%= render @topic.replies %>

<h2>Add a reply:</h2>
<% if session[:user_id] %>
  <%= form_for([@topic, @topic.replies.build]) do |f| %>
    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
<% else %>
  <%= link_to 'log in', url_for(:controller => :session, :action => :new) %>
  if you want to reply <br></br>
<% end %>
<%= link_to 'Back', topics_path %>
| <%= link_to 'Edit', edit_topic_path(@topic) %>